
-
    name: Synapse Client
    pip: name=synapseclient
-
    name: Tornado
    pip: name=tornado
-
    name: Download SMC Evaluation Tool
    git: dest=/opt/galaxy/SMC-Het-Challenge repo=https://github.com/Sage-Bionetworks/SMC-Het-Challenge.git
-
    name: Add SMC Evaluation Tool to Toolbox
    template: src=dev_tool_conf.xml.j2 dest={{ dev_tool_conf }}
-
    name: Replace small tool conf with empty conf
    template: src=tool_conf.small.xml.j2 dest={{ small_tool_conf_path }}
    when: small_tool_conf
- 
    name: Add Galaxy user to docker group - allowing sudoless docker usage
    user: name=ubuntu groups=docker append=yes
-
    name: Copy dream_galaxy_submit
    command: cp /opt/galaxy/SMC-Het-Challenge/dream_galaxy_submit /usr/bin/
-
    name: Add tool directory mounting command
    template: src=gce_mount_tool_disk.j2 dest=/usr/local/bin/gce_mount_tool_disk mode=a+x
-
    name: Add galaxy_lib_sync
    template: src=galaxy_lib_sync.py.j2 dest=/opt/galaxy/galaxy_lib_sync.py owner=ubuntu group=ubuntu mode="u=rx,g=rx,o="
-
    name: Add Auto Import supervisor configuration.
    template: src=galaxy_lib_sync_supervisor.conf.j2 dest=/etc/supervisor/conf.d/galaxy_lib_sync.conf
-
    name: Add galaxy lib sync supervisor configuration.
    template: src=galaxy_lib_sync_supervisor.conf.j2 dest=/etc/supervisor/conf.d/galaxy_lib_sync.conf
-
    name: Add submission server supervisor configuration.
    template: src=dream_submit_supervisor.conf.j2 dest=/etc/supervisor/conf.d/dream_submit_server.conf
-
    name: Add config for Submission Server
    template: src=nginx_submit.conf.j2 dest={{ nginx_conf_directory }}/submit.conf
-
    name: Make Data directory
    file: path=/opt/galaxy/data state=directory owner=ubuntu group=ubuntu mode="u=rxw,g=rxw,o=rx"
-
    name: Make Download directory
    file: path=/opt/galaxy/download state=directory owner=ubuntu group=ubuntu mode="u=rxw,g=rxw,o=rx"
-
    name: Download Example Data
    get_url: url={{ item }} dest=/opt/galaxy/download/
    with_items:
        - https://storage.googleapis.com/galaxyproject_images/Tumour2.tar.gz
        - https://storage.googleapis.com/galaxyproject_images/Tumour3.tar.gz
        - https://storage.googleapis.com/galaxyproject_images/Tumour4.tar.gz
        - https://storage.googleapis.com/galaxyproject_images/Tumour6.tar.gz
        - https://storage.googleapis.com/galaxyproject_images/Tumour7.tar.gz
-
    name: Unpack Training Data
    unarchive: src=/opt/galaxy/download/{{item}} dest=/opt/galaxy/data/ copy=no owner=ubuntu group=ubuntu
    with_items:
        - Tumour2.tar.gz
        - Tumour3.tar.gz
        - Tumour4.tar.gz
        - Tumour6.tar.gz
        - Tumour7.tar.gz
-
    name: chown data directory to ubuntu
    shell: chown -R ubuntu:ubuntu /opt/galaxy/data
-
    name: Evaluation tool data config
    template: src=smc_samples.loc.j2 dest=/opt/galaxy/galaxy-app/tool-data/smc_samples.loc owner=ubuntu group=ubuntu mode="u=r,g=r,o=r"
