
-
    name: Synapse Client
    pip: name=synapseclient
-
    name: Download SMC Evaluation Tool
    git: dest=/opt/galaxy/SMC-Het-Challenge repo=https://github.com/Sage-Bionetworks/SMC-Het-Challenge.git
-
    name: Add SMC Evaluation Tool to Toolbox
    template: src=dev_tool_conf.xml.j2 dest={{ dev_tool_conf }}
- 
    name: Replace small tool conf with empty conf
    template: src=tool_conf.small.xml.j2 dest={{ small_tool_conf_path }}
    when: small_tool_conf
-
    name: Copy dream_galaxy_submit
    command: cp /opt/galaxy/SMC-Het-Challenge/dream_galaxy_submit /usr/bin/
-
    name: Add galaxy_lib_sync
    template: src=galaxy_lib_sync.py.j2 dest=/opt/galaxy/galaxy_lib_sync.py owner=ubuntu group=ubuntu mode="u=rx,g=rx,o="
- 
    name: Add Auto Import supervisor configuration.
    template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/galaxy_lib_sync.conf

